import './GettingStarted_3_2.css';

// 1. Automatically scaffold the TypeScript interface
export interface GettingStarted_3_2Props {
    // Define props here
}

// 2. Clean, compiler-friendly functional component
export function GettingStarted_3_2({}: GettingStarted_3_2Props) {
    return (
        <div className="getting-started-3-2" data-node-id="162:2532">
            <header className="gs-header">
                <button aria-label="Go back" className="gs-back-button" type="button">
                    <span aria-hidden="true">&#8592;</span>
                </button>
                <h1>Getting Started</h1>
            </header>

            <main className="gs-main">
                <aside className="gs-steps" aria-label="Onboarding progress">
                    <ol>
                        <li className="is-complete">
                            <span className="gs-step-index gs-step-check" aria-hidden="true">
                                &#10003;
                            </span>
                            <span className="gs-step-label">Company Information</span>
                        </li>
                        <li className="is-complete">
                            <span className="gs-step-index gs-step-check" aria-hidden="true">
                                &#10003;
                            </span>
                            <span className="gs-step-label">Products Database</span>
                        </li>
                        <li className="is-complete">
                            <span className="gs-step-index gs-step-check" aria-hidden="true">
                                &#10003;
                            </span>
                            <span className="gs-step-label">Choose your Persona</span>
                        </li>
                    </ol>
                    <span className="gs-step-badge">Almost there...</span>
                </aside>

                <section className="gs-form-shell" aria-labelledby="persona-title">
                    <h2 id="persona-title">Persona Generation</h2>
                    <p>SociaLift provides persona for posts generation.</p>

                    <div className="gs-results">
                        <p className="gs-result-item">
                            <span className="gs-result-label">Final Persona:</span>
                            <span className="gs-result-value gs-highlight">
                                The Trusted Curator (Classic &amp; Reliable)
                            </span>
                        </p>

                        <p className="gs-result-item">
                            <span className="gs-result-label">Persona&apos;s Tone:</span>
                            <span className="gs-result-value gs-highlight">
                                Authoritative, warm, and polished.
                            </span>
                        </p>

                        <p className="gs-result-item gs-long-item">
                            <span className="gs-result-label">
                                Example Post Generated By This Persona:
                            </span>
                            <span className="gs-result-value gs-highlight">
                                Quality you can trust for the people who matter most. From Nike
                                active wear to Gini &amp; Jony play-ready outfits, we&apos;ve curated a
                                complete wardrobe solution for your modern family since 1998.
                            </span>
                        </p>
                    </div>

                    <button className="gs-done-button" type="button">
                        Done!
                    </button>
                </section>
            </main>
        </div>
    );
}