import './GettingStarted_3_3.css';

export interface GettingStarted_3_3Props {
    // Define props here
}

export function GettingStarted_3_3({}: GettingStarted_3_3Props) {
    return (
        <div className="getting-started-container">
            {/* HEADER */}
            <header className="gs-header">
                <button aria-label="Go back" className="gs-back-button" type="button">
                    <span aria-hidden="true">&#8592;</span>
                </button>
                <h1>Getting Started</h1>
            </header>

            <main className="gs-main-layout">
                {/* SIDEBAR */}
                <aside className="gs-sidebar">
                    <div className="gs-step is-complete">
                        <span className="gs-step-check">&#10003;</span>
                        <span className="gs-step-text">Company Information</span>
                    </div>

                    <div className="gs-step-dots">
                        <div className="gs-dot purple-dot"></div>
                        <div className="gs-dot purple-dot"></div>
                    </div>
                    
                    <div className="gs-step is-complete">
                        <span className="gs-step-check">&#10003;</span>
                        <span className="gs-step-text">Products Database</span>
                    </div>

                    
                    <div className="gs-step is-complete">
                        <span className="gs-step-check">&#10003;</span>
                        <span className="gs-step-text">Choose your Persona</span>
                    </div>

                    <div className="gs-step-dots">
                        <div className="gs-dot green-dot"></div>
                        <div className="gs-dot green-dot"></div>
                    </div>

                    <div className="gs-badge">Almost there...</div>
                </aside>

                {/* MAIN CONTENT CARD */}
                <section className="gs-form-card">
                    <h2 className="gs-title">Persona Generation</h2>
                    <p className="gs-subtitle">
                        SociaLift provides persona for posts generation.
                    </p>

                    <div className="gs-results">
                        <div className="gs-result-item">
                            <span className="gs-result-label">Final Persona:</span>
                            <span className="gs-result-value gs-highlight">
                                The Trusted Curator (Classic & Reliable)
                            </span>
                        </div>

                        <div className="gs-result-item">
                            <span className="gs-result-label">Persona's Tone:</span>
                            <span className="gs-result-value gs-highlight">
                                Authoritative, warm, and polished.
                            </span>
                        </div>

                        <div className="gs-result-item gs-long-item">
                            <span className="gs-result-label">
                                Example Post Generated By This Persona:
                            </span>
                            <span className="gs-result-value gs-highlight">
                                Quality you can trust for the people who matter most. From Nike
                                active wear to Gini & Jony play-ready outfits, we've curated a
                                complete wardrobe solution for your modern family since 1998.
                            </span>
                        </div>
                    </div>

                    <div className="gs-button-row">
                        <button className="gs-done-button" type="button">
                            Done!
                        </button>
                    </div>
                    
                </section>

                {/* OVERLAY & MODAL (Rendered inside main layout so it sits under the header) */}
                <div className="gs-overlay" aria-hidden="true" />

                <section className="gs-success-modal" aria-label="Success confirmation">
                    <div className="gs-success-icon" aria-hidden="true">
                        &#10003;
                    </div>
                    <h3>SUCCESS!</h3>
                    <p>
                        To view or modify your Information, Products Database, or Persona,
                        please navigate to your User Profile.
                    </p>
                    <button className="gs-success-continue" type="button">
                        Continue
                    </button>
                </section>
            </main>
        </div>
    );
}