module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "backgroundnav-bar-background": "var(--backgroundnav-bar-background)",
        black: "var(--black)",
        blue: "var(--blue)",
        bronze: "var(--bronze)",
        "facebookcolor-1": "var(--facebookcolor-1)",
        "facebookcolor-3": "var(--facebookcolor-3)",
        "facebookcolor-4": "var(--facebookcolor-4)",
        "facebookcolor-5": "var(--facebookcolor-5)",
        "facebookcolor-6": "var(--facebookcolor-6)",
        "facebookcolor-7": "var(--facebookcolor-7)",
        "facebookcolor-8": "var(--facebookcolor-8)",
        "facebookfacebook-blue": "var(--facebookfacebook-blue)",
        "facebookneutral-100": "var(--facebookneutral-100)",
        "gray-700": "var(--gray-700)",
        green: "var(--green)",
        "green-5": "var(--green-5)",
        "grey-blue-10": "var(--grey-blue-10)",
        "grey-blue-50": "var(--grey-blue-50)",
        "grey-blue-60": "var(--grey-blue-60)",
        "grey-blue-80": "var(--grey-blue-80)",
        "grey-blue-85": "var(--grey-blue-85)",
        "grey-blue-97": "var(--grey-blue-97)",
        "icon-05": "var(--icon-05)",
        "iconprimary-icon": "var(--iconprimary-icon)",
        "iconsecondary-icon": "var(--iconsecondary-icon)",
        "internal-fds-componentsmedia-inner-border":
          "var(--internal-fds-componentsmedia-inner-border)",
        orange: "var(--orange)",
        "orange-5": "var(--orange-5)",
        "persistentalways-white": "var(--persistentalways-white)",
        primari: "var(--primari)",
        purple: "var(--purple)",
        "purple-5": "var(--purple-5)",
        red: "var(--red)",
        "red-30": "var(--red-30)",
        "teal-blue": "var(--teal-blue)",
        "teal-blue-5": "var(--teal-blue-5)",
        "textprimary-text": "var(--textprimary-text)",
        "textsecondary-text": "var(--textsecondary-text)",
        tiffany: "var(--tiffany)",
        "tiffany-5": "var(--tiffany-5)",
        white: "var(--white)",
        "x-01": "var(--x-01)",
        yellow: "var(--yellow)",
        "yellow-5": "var(--yellow-5)",
      },
    },
  },
  plugins: [],
};